[package]
name = "amiya"
version = "0.1.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"

[dependencies]
smol = "0.1"
num_cpus = "1"
async-dup = "1"
http-types = "2"
futures = "0.3"
async-h1 = "2"
async-trait = "0.1"
