[package]
name = "amiya"
version = "0.1.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"

[dependencies]
smol = "0.1.18"
num_cpus = "1.13.0"
async-dup = "1.2.1"
http-types = "2.2.1"
futures = "0.3.5"
async-h1 = "2.1.0"
async-trait = "0.1.36"
